In [6]:
%load_ext autoreload
%autoreload 2

In [7]:
import bootstrap

REPO_ROOT /home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/multiplai/notebooks/../..


In [8]:
import json
import sys
import os
from multiplai import base
from multiplai.evals.nlu import data

import numpy as np
import mxnet as mx
from io import open
from mxnet import gluon, autograd
from mxnet.gluon import nn, rnn, Block
from mxnet import ndarray as F

from mxnet import gluon
from mxnet import nd
from mxnet.contrib import text
import collections

from multiplai.evals.nlu import embedding as emb

/home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/ve/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [9]:
TRAIN_DATA_PATH= 'multiplai/evals/nlu/nlu-benchmark/2017-06-custom-intent-engines/GetWeather/train_GetWeather_full.json'

In [10]:
train_data = data.load_train_data(TRAIN_DATA_PATH)

In [11]:
test_data = data.load_test_data(data.TEST_DATA_PATH)

In [12]:
train_data.keys()

dict_keys(['GetWeather'])

In [13]:
len(train_data['GetWeather'])

2000

In [14]:
all_text, all_entities = data.get_train_data_text_and_entities(data.load_train_data())

In [15]:
test_text, _ = data.get_train_data_text_and_entities(test_data)

In [16]:
all_text += "\n\n"+test_text

In [17]:
print(all_text)

What will the weather be this year in Horseshoe Lake State Fish and Wildlife Area ? 
Will it be sunny one hundred thirty five days from now in Monterey Bay National Marine Sanctuary
Is it supposed to rain nearby my current location at 0 o'clock ? 
what is the forecast starting on september 1 ,  2039 for chillier conditions in AK
how cold is it in Princeton Junction
weather in Nationalpark Nevado Tres Cruces on mar .  4th ,  2020
What will be wind speed in Tiplersville ,  South Sudan ? 
whats the weather in GA
what is the weather at my current location
Will it snow in Haigler Bosnia and Herzegovina
What is the weather in Åland 4 seconds from now
Will it snowstorm neighboring the Rio Grande Wild and Scenic River on feb .  the second ? 
what is the Sri Lanka forecast for snow
How is the weather going to be in Pearblossom . 
Can you tell me if it'll be freezing in Wrightstown in seven years  ? 
Is the weather going to be colder in GU in 11 years 
Will there be a snowstorm at my current pla

In [18]:
text.embedding.get_pretrained_file_names()


{'glove': ['glove.42B.300d.txt',
  'glove.6B.50d.txt',
  'glove.6B.100d.txt',
  'glove.6B.200d.txt',
  'glove.6B.300d.txt',
  'glove.840B.300d.txt',
  'glove.twitter.27B.25d.txt',
  'glove.twitter.27B.50d.txt',
  'glove.twitter.27B.100d.txt',
  'glove.twitter.27B.200d.txt'],
 'fasttext': ['crawl-300d-2M.vec',
  'wiki.aa.vec',
  'wiki.ab.vec',
  'wiki.ace.vec',
  'wiki.ady.vec',
  'wiki.af.vec',
  'wiki.ak.vec',
  'wiki.als.vec',
  'wiki.am.vec',
  'wiki.ang.vec',
  'wiki.an.vec',
  'wiki.arc.vec',
  'wiki.ar.vec',
  'wiki.arz.vec',
  'wiki.ast.vec',
  'wiki.as.vec',
  'wiki.av.vec',
  'wiki.ay.vec',
  'wiki.azb.vec',
  'wiki.az.vec',
  'wiki.bar.vec',
  'wiki.bat_smg.vec',
  'wiki.ba.vec',
  'wiki.bcl.vec',
  'wiki.be.vec',
  'wiki.bg.vec',
  'wiki.bh.vec',
  'wiki.bi.vec',
  'wiki.bjn.vec',
  'wiki.bm.vec',
  'wiki.bn.vec',
  'wiki.bo.vec',
  'wiki.bpy.vec',
  'wiki.br.vec',
  'wiki.bs.vec',
  'wiki.bug.vec',
  'wiki.bxr.vec',
  'wiki.ca.vec',
  'wiki.cbk_zam.vec',
  'wiki.cdo.vec',
 

In [19]:
embedding = emb.get_embedding_for_text(text_data=all_text)

/home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/ve/lib/python3.6/site-packages/mxnet/contrib/text/embedding.py:279: UserWarning: At line 1 of the pre-trained text embedding file: token 111051 with 1-dimensional vector [300.0] is likely a header and is skipped.
  'skipped.' % (line_num, token, elems))


In [20]:
embedding.token_to_idx['Victory']

874

In [21]:
embedding.token_to_idx[':']

38

In [22]:
sorted(embedding.token_to_idx.keys())

[',',
 '.',
 '/',
 '0',
 '00',
 '01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '1',
 '10',
 '10th',
 '11',
 '11th',
 '12',
 '129',
 '12th',
 '13',
 '131',
 '13th',
 '14',
 '14th',
 '15',
 '15th',
 '16',
 '165',
 '16th',
 '17',
 '175',
 '17th',
 '18',
 '188',
 '18th',
 '19',
 '19th',
 '1st',
 '2',
 '20',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2025',
 '2026',
 '2027',
 '2028',
 '2029',
 '2030',
 '2031',
 '2032',
 '2033',
 '2034',
 '2035',
 '2036',
 '2037',
 '2038',
 '2039',
 '2040',
 '20th',
 '21',
 '213',
 '21st',
 '22',
 '22nd',
 '23',
 '23rd',
 '24',
 '24th',
 '25',
 '257',
 '25th',
 '26',
 '26th',
 '27',
 '27th',
 '28',
 '28th',
 '29',
 '2nd',
 '3',
 '30',
 '308',
 '31',
 '32',
 '333',
 '34',
 '36',
 '365',
 '38',
 '3rd',
 '4',
 '40',
 '42',
 '43',
 '44',
 '45',
 '47',
 '48',
 '49',
 '4th',
 '5',
 '50',
 '52',
 '55',
 '56',
 '59',
 '5th',
 '6',
 '6th',
 '7',
 '7th',
 '8',
 '8th',
 '9',
 '9th',
 ':',
 '<unk>',
 '?',
 'A',
 'AK',
 'AL'

In [23]:
embedding.idx_to_vec.shape

(2324, 300)

In [24]:
len([row for row in embedding.idx_to_vec[:] if sum(row) == 0])

1963

In [25]:
good_indexes = [k for k, row in enumerate(embedding.idx_to_vec[:]) if sum(row) != 0]

In [26]:
[embedding.idx_to_token[idx] for idx in good_indexes]

['in',
 'the',
 'weather',
 'be',
 'it',
 'for',
 'forecast',
 '?',
 'is',
 'will',
 ',',
 'at',
 'on',
 'what',
 'to',
 'now',
 'from',
 '.',
 'me',
 'like',
 'there',
 'here',
 'a',
 'going',
 'current',
 'and',
 'my',
 '/',
 'of',
 'colder',
 'am',
 'chilly',
 'one',
 'get',
 'hot',
 'warm',
 'this',
 'freezing',
 'hotter',
 'next',
 'warmer',
 'cold',
 'pm',
 'if',
 'weeks',
 'around',
 'close',
 'minute',
 'minutes',
 'temperate',
 'position',
 'blizzard',
 'location',
 'area',
 'far',
 'place',
 'today',
 'week',
 'years',
 'hours',
 'need',
 'rain',
 'seconds',
 'hour',
 'same',
 'spot',
 'cloudy',
 'by',
 'windy',
 'within',
 'snowstorm',
 'storm',
 'conditions',
 'faraway',
 'hail',
 'days',
 'supposed',
 'three',
 'you',
 'humidity',
 'nearby',
 'second',
 'time',
 'months',
 'snowfall',
 'snowy',
 'stormy',
 'know',
 'show',
 'half',
 'cloud',
 'fog',
 'seven',
 'sunny',
 'day',
 'depression',
 'foggy',
 'six',
 'temps',
 'two',
 'humid',
 'rainy',
 'snow',
 'ten',
 'when',


### TODO:
- construct input variables
- construct target variables
- tweak training routine for simplified decoder structure
- construct a simple test case
    - maybe just observe training behavior on a small number of sequences that can converge and overfit very quickly?
- implement batching, then rerun the above test
- then try training for realsies
    

In [27]:
# print(example)
# data.example_to_training_pair(example, 
#                          data.get_word_to_idx(embedding),
#                          data.get_entity_to_idx(all_entities))
                         

In [28]:
# example['data'][0]['text'].strip().split(' ')

In [29]:
training_pairs = data.pairs_from_data(train_data['GetWeather'],
                                      all_entities=all_entities,
                                      embedding=embedding)

***************************************
chunk: {'text': "'s weather forecast for "}
chunk text split: ["'s", 'weather', 'forecast', 'for']
missing word: ''s'
example: {'data': [{'text': 'Give me '}, {'text': 'Slovakia', 'entity': 'country'}, {'text': "'s weather forecast for "}, {'text': 'eight am', 'entity': 'timeRange'}]}


In [30]:
test_pairs = data.pairs_from_data(data.load_test_data()['GetWeather'],
                                 all_entities=all_entities,
                                 embedding=embedding)

In [31]:
len(test_pairs)

100

In [32]:
# training_pairs

In [33]:
import multiplai.evals.nlu.model as model


In [34]:
n_words = len(embedding.token_to_idx.keys())
n_labels = len(all_entities)
n_words, n_labels

(2324, 9)

In [83]:
#ctx = mx.gpu(0)
ctx = mx.cpu()

# encoder = EncoderRNN(embedding, hidden_size=32)
# decoder = Decoder(n_labels, context_size=32)

classifier = model.ClassifierRNN(embedding, hidden_size=32, max_labels=n_labels)

In [36]:
model.train_iters(training_pairs, classifier, ctx)

/home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/ve/lib/python3.6/site-packages/mxnet/gluon/parameter.py:862: UserWarning: Parameter 'classifierrnn0_embedding0_weight' is already initialized, ignoring. Set force_reinit=True to re-initialize.
  v.initialize(None, ctx, init, force_reinit=force_reinit)


epoch 0 iteration 100  avg loss:  0.9899201172804643
epoch 0 iteration 200  avg loss:  0.5246720933480639
epoch 0 iteration 300  avg loss:  0.38387598057680294
epoch 0 iteration 400  avg loss:  0.3905548257161529
epoch 0 iteration 500  avg loss:  0.3878396820454201
epoch 0 iteration 600  avg loss:  0.31863214734618567
epoch 0 iteration 700  avg loss:  0.2924809538543051
epoch 0 iteration 800  avg loss:  0.24705282751039348
epoch 0 iteration 900  avg loss:  0.2779049663081987
epoch 0 iteration 1000  avg loss:  0.23151933807653793
epoch 0 iteration 1100  avg loss:  0.2526515826488025


KeyboardInterrupt: 

In [47]:
%debug

> /home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/multiplai/evals/nlu/model.py(110)train()
    108             loss = F.add(loss,
    109                          criterion(pred=classifier_outputs[di],
--> 110                                    labels=target_variable[di]))
    111             # print(criterion(decoder_outputs[di], target_variable[di]))
    112 

ipdb> criterion
SoftmaxCrossEntropyLoss(batch_axis=0, w=None)
ipdb> q


In [101]:
model.eval(training_pairs[0:], classifier, ctx, debug=False)

{'total_examples': 1999, 'total_example_errors': 1054, 'example_errors': {
  [[ 16   2   3   7   6  35  29  88   1 196  77   8]
   [  0   0   0   0   0   0   5   5   9   9   9   0]]
  <NDArray 2x12 @cpu(0)>, 
  [[  10   12    2    3    4  397   80   21   20   21    2  790 1673  155
      34   30]
   [   0    0    0    0    0    9    9    9    9    0    0    6    6    6
       6    6]]
  <NDArray 2x16 @cpu(0)>, 
  [[11  5  4 40 26 44 64 21 20]
   [ 0  0  0  3  5  9  9  9  9]]
  <NDArray 2x9 @cpu(0)>, 
  [[10 12  2  3  4 24 41 64 21 20 95  2 87 71 37 35 29 69]
   [ 0  0  0  0  0  0  9  9  9  9  7  7  7  7  0  0  5  5]]
  <NDArray 2x18 @cpu(0)>, 
  [[  16    2    3    7    6 1619  244  577   14  231   38  679]
   [   0    0    0    0    0    1    4    4    0    9    9    9]]
  <NDArray 2x12 @cpu(0)>, 
  [[ 16   2   3   7   6  26   1 332   8]
   [  0   0   0   0   0   5   0   9   0]]
  <NDArray 2x9 @cpu(0)>, 
  [[ 137    2    3    6 1562   13  632    6   61  171   42]
   [   0    0    0   

In [102]:
model.eval(test_pairs[0:], classifier, ctx, debug=False)

{'total_examples': 100, 'total_example_errors': 74, 'example_errors': {
  [[  10    9    2    3    7    6 1125]
   [   0    0    0    0    0    0    4]]
  <NDArray 2x7 @cpu(0)>, 
  [[  10    9    2    7    6   48  637    6   68  104    1 1279  558]
   [   0    0    0    0    0    0    9    0    2    0    0    1    4]]
  <NDArray 2x13 @cpu(0)>, 
  [[  10   12    2    3    4    1  341   22    1 1116    8]
   [   0    0    0    0    0    0    9    9    0    1    0]]
  <NDArray 2x11 @cpu(0)>, 
  [[  10   12    2    3    4    1 1252   17  294   22    2  335   13  212
       8]
   [   0    0    0    0    0    0    1    0    9    9    9    9    9    9
       0]]
  <NDArray 2x15 @cpu(0)>, 
  [[  10   12    2    3    4    1 1468  759   17  275    2  524    8]
   [   0    0    0    0    0    0    1    1    0    9    9    9    0]]
  <NDArray 2x13 @cpu(0)>, 
  [[  10   12    2    3    4    1 1964  186   17  332  147   13  255    8]
   [   0    0    0    0    0    0    6    6    0    9    9    9   

In [39]:
%debug

> /home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/ve/lib/python3.6/site-packages/mxnet/base.py(253)check_call()
    251     """
    252     if ret != 0:
--> 253         raise MXNetError(py_str(_LIB.MXGetLastError()))
    254 
    255 

ipdb> q


In [45]:
data.get_entity_to_idx(all_entities)

{'<none>': 0,
 'city': 1,
 'condition_description': 2,
 'condition_temperature': 3,
 'country': 4,
 'current_location': 5,
 'geographic_poi': 6,
 'spatial_relation': 7,
 'state': 8,
 'timeRange': 9}

In [ ]:
# NEXT STEPS:
# x  test on actual test data, not just training data



# lower case everything...most of teh crap in wordvec in zero anyway! 
# maybe load glove?
# - print train accuracy and test acc after each epoch
#
# maybe give up on existing embeddings and train a separate (char) RNN
#   - could train a next-char predictor to get unsupervised feature extraction from large background corpus
#   - this might be a great level-2 proof of concept once the meta learning thing works at all

# overall: 
# - simple predictor does work and gets trained on this data set
# - some cues are confusing given lack of distinct embeddings for times and places
#
# - question: how good do i actually need to make the simple model here?
# - train it on multiple intents?
# -


In [4]:
obs = 1


In [98]:
classifier.initialize(force_reinit=True)

In [99]:
classifier.collect_params()

classifierrnn1_ (
  Parameter classifierrnn1_embedding0_weight (shape=(2324, 300), dtype=float32)
  Parameter classifierrnn1_gru0_l0_i2h_weight (shape=(96, 300), dtype=float32)
  Parameter classifierrnn1_gru0_l0_h2h_weight (shape=(96, 32), dtype=float32)
  Parameter classifierrnn1_gru0_l0_i2h_bias (shape=(96,), dtype=float32)
  Parameter classifierrnn1_gru0_l0_h2h_bias (shape=(96,), dtype=float32)
  Parameter classifierrnn1_dense0_weight (shape=(9, 32), dtype=float32)
  Parameter classifierrnn1_dense0_bias (shape=(9,), dtype=float32)
)

In [100]:
values = [v for v in classifier.collect_params().values()]
values

[Parameter classifierrnn1_embedding0_weight (shape=(2324, 300), dtype=float32),
 Parameter classifierrnn1_gru0_l0_i2h_weight (shape=(96, 300), dtype=float32),
 Parameter classifierrnn1_gru0_l0_h2h_weight (shape=(96, 32), dtype=float32),
 Parameter classifierrnn1_gru0_l0_i2h_bias (shape=(96,), dtype=float32),
 Parameter classifierrnn1_gru0_l0_h2h_bias (shape=(96,), dtype=float32),
 Parameter classifierrnn1_dense0_weight (shape=(9, 32), dtype=float32),
 Parameter classifierrnn1_dense0_bias (shape=(9,), dtype=float32)]

In [101]:
2324*300 + 96*300 + 96*32 + 96 +96+9*32+9

729561

In [102]:
d = values[0].data()
d


[[ 0.02638481 -0.02880274  0.06674667 ...  0.04094984  0.00746413
   0.04699045]
 [ 0.01073194 -0.00231574 -0.02580607 ... -0.04947828 -0.06608752
   0.05868394]
 [-0.01951114 -0.0123723  -0.04481311 ...  0.06927506 -0.04411322
  -0.03896664]
 ...
 [ 0.0389752   0.03544502  0.03526814 ...  0.03758648 -0.06630425
   0.05263385]
 [-0.05905983  0.03760964  0.06967182 ... -0.04506121  0.00220135
  -0.01483657]
 [-0.06689225 -0.04050173  0.02077558 ... -0.03117625  0.03834612
  -0.002716  ]]
<NDArray 2324x300 @cpu(0)>

In [81]:
values[0].set_data(100*d)

In [69]:
d.reshape((-1,))


[ 0.          0.          0.         ...  0.0479841  -0.13532107
 -0.06245235]
<NDArray 697200 @cpu(0)>

In [73]:
nd.concatenate([v.data().reshape((-1,)) for v in values])


[ 0.          0.          0.         ...  0.49293098 -0.8589942
  1.2846965 ]
<NDArray 729561 @cpu(0)>

In [103]:
def _get_from_flat(block) -> nd.array:
    values = [v for v in block.collect_params().values()]
    flat = nd.concatenate([v.data().reshape((-1,)) for v in values])
    return flat

In [106]:
w_flat = _get_from_flat(classifier)
w_flat


[ 0.02638481 -0.02880274  0.06674667 ...  0.          0.
  0.        ]
<NDArray 729561 @cpu(0)>

In [108]:
np.allclose(w_flat.asnumpy(), w_flat.asnumpy())

True