In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import bootstrap

REPO_ROOT /home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/multiplai/notebooks/../..


In [3]:
import json
import sys
import os
from multiplai import base
from multiplai.evals.nlu import data

import numpy as np
import mxnet as mx
from io import open
from mxnet import gluon, autograd
from mxnet.gluon import nn, rnn, Block
from mxnet import ndarray as F

from mxnet import gluon
from mxnet import nd
from mxnet.contrib import text
import collections

from multiplai.evals.nlu import embedding as emb

/home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/ve/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
TRAIN_DATA_PATH= 'multiplai/evals/nlu/nlu-benchmark/2017-06-custom-intent-engines/GetWeather/train_GetWeather_full.json'

In [5]:
train_data = data.load_train_data(TRAIN_DATA_PATH)

In [6]:
test_data = data.load_test_data(data.TEST_DATA_PATH)

In [7]:
train_data.keys()

dict_keys(['GetWeather'])

In [8]:
len(train_data['GetWeather'])

2000

In [9]:
all_text, all_entities = data.get_train_data_text_and_entities(data.load_train_data())

In [10]:
test_text, _ = data.get_train_data_text_and_entities(test_data)

In [11]:
all_text += "\n\n"+test_text

In [12]:
print(all_text)

What will the weather be this year in Horseshoe Lake State Fish and Wildlife Area ? 
Will it be sunny one hundred thirty five days from now in Monterey Bay National Marine Sanctuary
Is it supposed to rain nearby my current location at 0 o'clock ? 
what is the forecast starting on september 1 ,  2039 for chillier conditions in AK
how cold is it in Princeton Junction
weather in Nationalpark Nevado Tres Cruces on mar .  4th ,  2020
What will be wind speed in Tiplersville ,  South Sudan ? 
whats the weather in GA
what is the weather at my current location
Will it snow in Haigler Bosnia and Herzegovina
What is the weather in Åland 4 seconds from now
Will it snowstorm neighboring the Rio Grande Wild and Scenic River on feb .  the second ? 
what is the Sri Lanka forecast for snow
How is the weather going to be in Pearblossom . 
Can you tell me if it'll be freezing in Wrightstown in seven years  ? 
Is the weather going to be colder in GU in 11 years 
Will there be a snowstorm at my current pla

In [13]:
text.embedding.get_pretrained_file_names()


{'glove': ['glove.42B.300d.txt',
  'glove.6B.50d.txt',
  'glove.6B.100d.txt',
  'glove.6B.200d.txt',
  'glove.6B.300d.txt',
  'glove.840B.300d.txt',
  'glove.twitter.27B.25d.txt',
  'glove.twitter.27B.50d.txt',
  'glove.twitter.27B.100d.txt',
  'glove.twitter.27B.200d.txt'],
 'fasttext': ['crawl-300d-2M.vec',
  'wiki.aa.vec',
  'wiki.ab.vec',
  'wiki.ace.vec',
  'wiki.ady.vec',
  'wiki.af.vec',
  'wiki.ak.vec',
  'wiki.als.vec',
  'wiki.am.vec',
  'wiki.ang.vec',
  'wiki.an.vec',
  'wiki.arc.vec',
  'wiki.ar.vec',
  'wiki.arz.vec',
  'wiki.ast.vec',
  'wiki.as.vec',
  'wiki.av.vec',
  'wiki.ay.vec',
  'wiki.azb.vec',
  'wiki.az.vec',
  'wiki.bar.vec',
  'wiki.bat_smg.vec',
  'wiki.ba.vec',
  'wiki.bcl.vec',
  'wiki.be.vec',
  'wiki.bg.vec',
  'wiki.bh.vec',
  'wiki.bi.vec',
  'wiki.bjn.vec',
  'wiki.bm.vec',
  'wiki.bn.vec',
  'wiki.bo.vec',
  'wiki.bpy.vec',
  'wiki.br.vec',
  'wiki.bs.vec',
  'wiki.bug.vec',
  'wiki.bxr.vec',
  'wiki.ca.vec',
  'wiki.cbk_zam.vec',
  'wiki.cdo.vec',
 

In [14]:
embedding = emb.get_embedding_for_text(text_data=all_text)

/home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/ve/lib/python3.6/site-packages/mxnet/contrib/text/embedding.py:279: UserWarning: At line 1 of the pre-trained text embedding file: token 111051 with 1-dimensional vector [300.0] is likely a header and is skipped.
  'skipped.' % (line_num, token, elems))


In [15]:
embedding.token_to_idx['Victory']

874

In [16]:
embedding.token_to_idx[':']

38

In [17]:
sorted(embedding.token_to_idx.keys())

[',',
 '.',
 '/',
 '0',
 '00',
 '01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '1',
 '10',
 '10th',
 '11',
 '11th',
 '12',
 '129',
 '12th',
 '13',
 '131',
 '13th',
 '14',
 '14th',
 '15',
 '15th',
 '16',
 '165',
 '16th',
 '17',
 '175',
 '17th',
 '18',
 '188',
 '18th',
 '19',
 '19th',
 '1st',
 '2',
 '20',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2025',
 '2026',
 '2027',
 '2028',
 '2029',
 '2030',
 '2031',
 '2032',
 '2033',
 '2034',
 '2035',
 '2036',
 '2037',
 '2038',
 '2039',
 '2040',
 '20th',
 '21',
 '213',
 '21st',
 '22',
 '22nd',
 '23',
 '23rd',
 '24',
 '24th',
 '25',
 '257',
 '25th',
 '26',
 '26th',
 '27',
 '27th',
 '28',
 '28th',
 '29',
 '2nd',
 '3',
 '30',
 '308',
 '31',
 '32',
 '333',
 '34',
 '36',
 '365',
 '38',
 '3rd',
 '4',
 '40',
 '42',
 '43',
 '44',
 '45',
 '47',
 '48',
 '49',
 '4th',
 '5',
 '50',
 '52',
 '55',
 '56',
 '59',
 '5th',
 '6',
 '6th',
 '7',
 '7th',
 '8',
 '8th',
 '9',
 '9th',
 ':',
 '<unk>',
 '?',
 'A',
 'AK',
 'AL'

In [18]:
embedding.idx_to_vec.shape

(2324, 300)

In [19]:
len([row for row in embedding.idx_to_vec[:] if sum(row) == 0])

1963

In [20]:
good_indexes = [k for k, row in enumerate(embedding.idx_to_vec[:]) if sum(row) != 0]

In [21]:
[embedding.idx_to_token[idx] for idx in good_indexes]

['in',
 'the',
 'weather',
 'be',
 'it',
 'for',
 'forecast',
 '?',
 'is',
 'will',
 ',',
 'at',
 'on',
 'what',
 'to',
 'now',
 'from',
 '.',
 'me',
 'like',
 'there',
 'here',
 'a',
 'going',
 'current',
 'and',
 'my',
 '/',
 'of',
 'colder',
 'am',
 'chilly',
 'one',
 'get',
 'hot',
 'warm',
 'this',
 'freezing',
 'hotter',
 'next',
 'warmer',
 'cold',
 'pm',
 'if',
 'weeks',
 'around',
 'close',
 'minute',
 'minutes',
 'temperate',
 'position',
 'blizzard',
 'location',
 'area',
 'far',
 'place',
 'today',
 'week',
 'years',
 'hours',
 'need',
 'rain',
 'seconds',
 'hour',
 'same',
 'spot',
 'cloudy',
 'by',
 'windy',
 'within',
 'snowstorm',
 'storm',
 'conditions',
 'faraway',
 'hail',
 'days',
 'supposed',
 'three',
 'you',
 'humidity',
 'nearby',
 'second',
 'time',
 'months',
 'snowfall',
 'snowy',
 'stormy',
 'know',
 'show',
 'half',
 'cloud',
 'fog',
 'seven',
 'sunny',
 'day',
 'depression',
 'foggy',
 'six',
 'temps',
 'two',
 'humid',
 'rainy',
 'snow',
 'ten',
 'when',


### TODO:
- construct input variables
- construct target variables
- tweak training routine for simplified decoder structure
- construct a simple test case
    - maybe just observe training behavior on a small number of sequences that can converge and overfit very quickly?
- implement batching, then rerun the above test
- then try training for realsies
    

In [22]:
# print(example)
# data.example_to_training_pair(example, 
#                          data.get_word_to_idx(embedding),
#                          data.get_entity_to_idx(all_entities))
                         

In [23]:
# example['data'][0]['text'].strip().split(' ')

In [24]:
training_pairs = data.pairs_from_data(train_data['GetWeather'],
                                      all_entities=all_entities,
                                      embedding=embedding)

***************************************
chunk: {'text': "'s weather forecast for "}
chunk text split: ["'s", 'weather', 'forecast', 'for']
missing word: ''s'
example: {'data': [{'text': 'Give me '}, {'text': 'Slovakia', 'entity': 'country'}, {'text': "'s weather forecast for "}, {'text': 'eight am', 'entity': 'timeRange'}]}


In [25]:
test_pairs = data.pairs_from_data(data.load_test_data()['GetWeather'],
                                 all_entities=all_entities,
                                 embedding=embedding)

In [26]:
len(test_pairs)

100

In [27]:
# training_pairs

In [28]:
import multiplai.evals.nlu.model as model


In [29]:
n_words = len(embedding.token_to_idx.keys())
n_labels = len(all_entities)
n_words, n_labels

(2324, 9)

In [30]:
#ctx = mx.gpu(0)
ctx = mx.cpu()

# encoder = EncoderRNN(embedding, hidden_size=32)
# decoder = Decoder(n_labels, context_size=32)

classifier = model.ClassifierRNN(embedding, hidden_size=32, max_labels=n_labels)

In [31]:
model.train_iters(training_pairs, classifier, ctx)

/home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/ve/lib/python3.6/site-packages/mxnet/gluon/parameter.py:862: UserWarning: Parameter 'classifierrnn0_embedding0_weight' is already initialized, ignoring. Set force_reinit=True to re-initialize.
  v.initialize(None, ctx, init, force_reinit=force_reinit)


epoch 0 iteration 100  avg loss:  0.9899201172804643
epoch 0 iteration 200  avg loss:  0.5246720933480639
epoch 0 iteration 300  avg loss:  0.38387598057680294
epoch 0 iteration 400  avg loss:  0.3905548257161529
epoch 0 iteration 500  avg loss:  0.3878396820454201
epoch 0 iteration 600  avg loss:  0.31863214734618567
epoch 0 iteration 700  avg loss:  0.2924809538543051
epoch 0 iteration 800  avg loss:  0.24705282751039348
epoch 0 iteration 900  avg loss:  0.2779049663081987
epoch 0 iteration 1000  avg loss:  0.23151933807653793
epoch 0 iteration 1100  avg loss:  0.2526515826488025
epoch 0 iteration 1200  avg loss:  0.27261232788006867
epoch 0 iteration 1300  avg loss:  0.236535806311848
epoch 0 iteration 1400  avg loss:  0.2704311112234382
epoch 0 iteration 1500  avg loss:  0.2551406154729865
epoch 0 iteration 1600  avg loss:  0.24586302381495517
epoch 0 iteration 1700  avg loss:  0.2114286073654111
epoch 0 iteration 1800  avg loss:  0.24745367022708312
epoch 0 iteration 1900  avg los

epoch 7 iteration 1900  avg loss:  0.025293319212043506
epoch 8 iteration 100  avg loss:  0.10225813031295436
epoch 8 iteration 200  avg loss:  0.034494678727476906
epoch 8 iteration 300  avg loss:  0.021482441045379542
epoch 8 iteration 400  avg loss:  0.04334198493362856
epoch 8 iteration 500  avg loss:  0.04498717350460745
epoch 8 iteration 600  avg loss:  0.02476089017220502
epoch 8 iteration 700  avg loss:  0.03554998972052418
epoch 8 iteration 800  avg loss:  0.023841193231165687
epoch 8 iteration 900  avg loss:  0.03422364487473572
epoch 8 iteration 1000  avg loss:  0.03128729528433522
epoch 8 iteration 1100  avg loss:  0.03200155667570416
epoch 8 iteration 1200  avg loss:  0.027737373717436013
epoch 8 iteration 1300  avg loss:  0.04256931510274727
epoch 8 iteration 1400  avg loss:  0.03437703765799969
epoch 8 iteration 1500  avg loss:  0.03820492994334962
epoch 8 iteration 1600  avg loss:  0.03967117998162643
epoch 8 iteration 1700  avg loss:  0.02298943717350363
epoch 8 iterat

epoch 15 iteration 1400  avg loss:  0.012885377223168785
epoch 15 iteration 1500  avg loss:  0.026355351144551575
epoch 15 iteration 1600  avg loss:  0.03088523582399971
epoch 15 iteration 1700  avg loss:  0.018586831010805552
epoch 15 iteration 1800  avg loss:  0.0182042271017575
epoch 15 iteration 1900  avg loss:  0.0054436089151663316
epoch 16 iteration 100  avg loss:  0.04291153765189804
epoch 16 iteration 200  avg loss:  0.016329526852556554
epoch 16 iteration 300  avg loss:  0.008309224004550466
epoch 16 iteration 400  avg loss:  0.014887267251955352
epoch 16 iteration 500  avg loss:  0.022491485289508274
epoch 16 iteration 600  avg loss:  0.013055451512204353
epoch 16 iteration 700  avg loss:  0.01839371812897276
epoch 16 iteration 800  avg loss:  0.011209609117228124
epoch 16 iteration 900  avg loss:  0.019159669008482476
epoch 16 iteration 1000  avg loss:  0.025039680727367255
epoch 16 iteration 1100  avg loss:  0.007924587372056549
epoch 16 iteration 1200  avg loss:  0.015062

epoch 23 iteration 1000  avg loss:  0.05373785638505117
epoch 23 iteration 1100  avg loss:  0.0453854575892907
epoch 23 iteration 1200  avg loss:  0.04747821903773078
epoch 23 iteration 1300  avg loss:  0.06663824379440673
epoch 23 iteration 1400  avg loss:  0.04515304208329875
epoch 23 iteration 1500  avg loss:  0.06314151297629267
epoch 23 iteration 1600  avg loss:  0.05235203245607793
epoch 23 iteration 1700  avg loss:  0.04316475290443228
epoch 23 iteration 1800  avg loss:  0.04806815388699155
epoch 23 iteration 1900  avg loss:  0.032624649204612464
epoch 24 iteration 100  avg loss:  0.08432974361575753
epoch 24 iteration 200  avg loss:  0.048219320472150475
epoch 24 iteration 300  avg loss:  0.023838398351569104
epoch 24 iteration 400  avg loss:  0.03831397568598198
epoch 24 iteration 500  avg loss:  0.05856438734773655
epoch 24 iteration 600  avg loss:  0.038088748844565236
epoch 24 iteration 700  avg loss:  0.037891952307473456
epoch 24 iteration 800  avg loss:  0.02685080941075

epoch 31 iteration 500  avg loss:  0.01376927909614053
epoch 31 iteration 600  avg loss:  0.016302117140039377
epoch 31 iteration 700  avg loss:  0.017963627679939153
epoch 31 iteration 800  avg loss:  0.012038371421500962
epoch 31 iteration 900  avg loss:  0.021694918939905907
epoch 31 iteration 1000  avg loss:  0.017804990819908856
epoch 31 iteration 1100  avg loss:  0.0056488959848931776
epoch 31 iteration 1200  avg loss:  0.019320527738998193
epoch 31 iteration 1300  avg loss:  0.02635952731818043
epoch 31 iteration 1400  avg loss:  0.011116822130816948
epoch 31 iteration 1500  avg loss:  0.026784051300499413
epoch 31 iteration 1600  avg loss:  0.02002427797056833
epoch 31 iteration 1700  avg loss:  0.015391291603771128
epoch 31 iteration 1800  avg loss:  0.02294558216882367
epoch 31 iteration 1900  avg loss:  0.0030860921130575303
epoch 32 iteration 100  avg loss:  0.03689179020126815
epoch 32 iteration 200  avg loss:  0.027251066104163137
epoch 32 iteration 300  avg loss:  0.0059

KeyboardInterrupt: 

In [ ]:
# with frozen embedding weights:
# epoch 26 iteration 1600  avg loss:  0.4815173112378105
# test error:  'total_words': 1067, 'word_errors': 322}

# without frozen embedding weights:
# epoch 26 iteration 1600  avg loss:  0.02683571884008783
# epoch 33 iteration 100  avg loss:  0.03545082483602533
# 'total_words': 1067, 'word_errors': 244}

In [ ]:
%debug

In [ ]:
model.eval(training_pairs[0:], classifier, ctx, debug=False)

In [32]:
model.eval(test_pairs[0:], classifier, ctx, debug=False)

{'total_examples': 100, 'total_example_errors': 81, 'example_errors': {
  [[  10    9    2    3    7    6 1125]
   [   0    0    0    0    0    0    4]]
  <NDArray 2x7 @cpu(0)>, 
  [[  10    9    2    7    6   48  637    6   68  104    1 1279  558]
   [   0    0    0    0    0    0    9    0    2    0    0    1    4]]
  <NDArray 2x13 @cpu(0)>, 
  [[  10   12    2    3    4    1  341   22    1 1116    8]
   [   0    0    0    0    0    0    9    9    0    1    0]]
  <NDArray 2x11 @cpu(0)>, 
  [[  10   12    2    3    4    1 1252   17  294   22    2  335   13  212
       8]
   [   0    0    0    0    0    0    1    0    9    9    9    9    9    9
       0]]
  <NDArray 2x15 @cpu(0)>, 
  [[  10   12    2    3    4    1 1468  759   17  275    2  524    8]
   [   0    0    0    0    0    0    1    1    0    9    9    9    0]]
  <NDArray 2x13 @cpu(0)>, 
  [[  10   12    2    3    4    1 1964  186   17  332  147   13  255    8]
   [   0    0    0    0    0    0    6    6    0    9    9    9   

In [ ]:
%debug

In [ ]:
data.get_entity_to_idx(all_entities)

In [ ]:
# NEXT STEPS:
# x  test on actual test data, not just training data



# lower case everything...most of teh crap in wordvec in zero anyway! 
# maybe load glove?
# - print train accuracy and test acc after each epoch
#
# maybe give up on existing embeddings and train a separate (char) RNN
#   - could train a next-char predictor to get unsupervised feature extraction from large background corpus
#   - this might be a great level-2 proof of concept once the meta learning thing works at all

# overall: 
# - simple predictor does work and gets trained on this data set
# - some cues are confusing given lack of distinct embeddings for times and places
#
# - question: how good do i actually need to make the simple model here?
# - train it on multiple intents?
# -


In [ ]:
obs = 1


In [ ]:
classifier.initialize(force_reinit=True)

In [ ]:
classifier.collect_params()

In [ ]:
values = [v for v in classifier.collect_params().values()]
values

In [ ]:
2324*300 + 96*300 + 96*32 + 96 +96+9*32+9

In [ ]:
d = values[0].data()
d

In [ ]:
values[0].set_data(100*d)

In [ ]:
d.reshape((-1,))

In [ ]:
nd.concatenate([v.data().reshape((-1,)) for v in values])

In [ ]:
def _get_from_flat(block) -> nd.array:
    values = [v for v in block.collect_params().values()]
    flat = nd.concatenate([v.data().reshape((-1,)) for v in values])
    return flat

In [ ]:
w_flat = _get_from_flat(classifier)
w_flat

In [ ]:
np.allclose(w_flat.asnumpy(), w_flat.asnumpy())

In [ ]:
params = classifier.collect_params()

In [ ]:

for k,v in params.items():
    print(k,v)
#     if v.grad_req != 'null':
    print('grad_req =', v.grad_req)
#         print("trainable")
        
    print("--------------------------")

In [ ]:
v.__dict__

In [ ]:
classifier.summary()

In [ ]:
classifier.initialize()

In [ ]:
hidden = classifier.init_hidden(mx.cpu(0))

In [ ]:
classifier.summary(hidden[0], hidden)

In [41]:
'embedding' in [v for v in classifier.collect_params().values()][0].name

True

In [49]:
np.array([10,10])[None].shape

(1, 2)

In [46]:
10[None]

TypeError: 'int' object is not subscriptable