In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import bootstrap

REPO_ROOT /home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/multiplai/notebooks/../..


In [3]:
import json
import sys
import os
from multiplai import base
from multiplai.evals.nlu import data

/home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/ve/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
TRAIN_DATA_PATH= 'multiplai/evals/nlu/nlu-benchmark/2017-06-custom-intent-engines/GetWeather/train_GetWeather_full.json'

In [5]:
train_data = data.load_train_data(TRAIN_DATA_PATH)

In [6]:
# construct examples

In [7]:
from dataclasses import dataclass

In [8]:
@dataclass
class Example():
    a: int
        

In [9]:
train_data.keys()

dict_keys(['GetWeather'])

In [10]:
len(train_data['GetWeather'])

2000

In [11]:
from multiplai.evals.nlu import data
all_text, all_entities = data.get_train_data_text_and_entities(data.load_train_data())

In [12]:
print(all_text)

What will the weather be this year in Horseshoe Lake State Fish and Wildlife Area ? 
Will it be sunny one hundred thirty five days from now in Monterey Bay National Marine Sanctuary
Is it supposed to rain nearby my current location at 0 o'clock ? 
what is the forecast starting on september 1 ,  2039 for chillier conditions in AK
how cold is it in Princeton Junction
weather in Nationalpark Nevado Tres Cruces on mar .  4th ,  2020
What will be wind speed in Tiplersville ,  South Sudan ? 
whats the weather in GA
what is the weather at my current location
Will it snow in Haigler Bosnia and Herzegovina
What is the weather in Åland 4 seconds from now
Will it snowstorm neighboring the Rio Grande Wild and Scenic River on feb .  the second ? 
what is the Sri Lanka forecast for snow
How is the weather going to be in Pearblossom . 
Can you tell me if it'll be freezing in Wrightstown in seven years  ? 
Is the weather going to be colder in GU in 11 years 
Will there be a snowstorm at my current pla

In [13]:
import numpy as np
import mxnet as mx
from io import open
from mxnet import gluon, autograd
from mxnet.gluon import nn, rnn, Block
from mxnet import ndarray as F

In [14]:
from mxnet import gluon
from mxnet import nd
from mxnet.contrib import text
import collections

In [15]:
from multiplai.evals.nlu import embedding as emb

In [16]:
embedding = emb.get_embedding_for_text(text_data=all_text)

/home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/ve/lib/python3.6/site-packages/mxnet/contrib/text/embedding.py:279: UserWarning: At line 1 of the pre-trained text embedding file: token 111051 with 1-dimensional vector [300.0] is likely a header and is skipped.
  'skipped.' % (line_num, token, elems))


In [17]:
embedding.token_to_idx['Victory']

848

In [18]:
embedding.token_to_idx[':']

38

In [19]:
sorted(embedding.token_to_idx.keys())

[',',
 '.',
 '/',
 '0',
 '00',
 '01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '1',
 '10',
 '10th',
 '11',
 '11th',
 '12',
 '129',
 '12th',
 '13',
 '131',
 '13th',
 '14',
 '14th',
 '15',
 '15th',
 '16',
 '165',
 '17',
 '175',
 '17th',
 '18',
 '188',
 '18th',
 '19',
 '19th',
 '1st',
 '2',
 '20',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2025',
 '2026',
 '2027',
 '2028',
 '2029',
 '2030',
 '2031',
 '2032',
 '2033',
 '2034',
 '2035',
 '2036',
 '2037',
 '2038',
 '2039',
 '2040',
 '20th',
 '21',
 '213',
 '21st',
 '22',
 '22nd',
 '23',
 '23rd',
 '24',
 '24th',
 '25',
 '257',
 '25th',
 '26',
 '26th',
 '27',
 '27th',
 '28',
 '28th',
 '2nd',
 '3',
 '30',
 '308',
 '31',
 '32',
 '333',
 '34',
 '36',
 '365',
 '38',
 '3rd',
 '4',
 '40',
 '42',
 '43',
 '44',
 '45',
 '47',
 '48',
 '49',
 '4th',
 '5',
 '50',
 '52',
 '55',
 '56',
 '59',
 '5th',
 '6',
 '6th',
 '7',
 '7th',
 '8',
 '8th',
 '9',
 '9th',
 ':',
 '<unk>',
 '?',
 'A',
 'AK',
 'AL',
 'AM',
 'AMari

In [20]:
embedding.idx_to_vec.shape

(2262, 300)

### TODO:
- construct input variables
- construct target variables
- tweak training routine for simplified decoder structure
- construct a simple test case
    - maybe just observe training behavior on a small number of sequences that can converge and overfit very quickly?
- implement batching, then rerun the above test
- then try training for realsies
    

In [22]:
# print(example)
# data.example_to_training_pair(example, 
#                          data.get_word_to_idx(embedding),
#                          data.get_entity_to_idx(all_entities))
                         

In [23]:
# example['data'][0]['text'].strip().split(' ')

In [24]:
training_pairs = [data.example_to_training_pair(example, 
                      data.get_word_to_idx(embedding),
                      data.get_entity_to_idx(all_entities))
                  for example in train_data['GetWeather']                
                 ]
training_pairs = [tp for tp in training_pairs if tp != []]


***************************************
chunk: {'text': "'s weather forecast for "}
chunk text split: ["'s", 'weather', 'forecast', 'for']
missing word: ''s'
example: {'data': [{'text': 'Give me '}, {'text': 'Slovakia', 'entity': 'country'}, {'text': "'s weather forecast for "}, {'text': 'eight am', 'entity': 'timeRange'}]}


In [25]:
training_pairs

[[(10, 0),
  (12, 0),
  (2, 0),
  (3, 0),
  (4, 0),
  (48, 9),
  (154, 9),
  (1, 0),
  (1439, 6),
  (81, 6),
  (34, 6),
  (741, 6),
  (35, 6),
  (60, 6),
  (100, 6),
  (8, 0)],
 [(11, 0),
  (5, 0),
  (4, 0),
  (128, 2),
  (46, 9),
  (237, 9),
  (885, 9),
  (157, 9),
  (103, 9),
  (21, 9),
  (20, 9),
  (1, 0),
  (568, 6),
  (187, 6),
  (33, 6),
  (431, 6),
  (189, 6)],
 [(15, 0),
  (5, 0),
  (106, 0),
  (17, 0),
  (78, 2),
  (127, 7),
  (32, 0),
  (29, 5),
  (67, 5),
  (14, 0),
  (387, 9),
  (87, 9),
  (8, 0)],
 [(19, 0),
  (9, 0),
  (2, 0),
  (7, 0),
  (219, 0),
  (18, 0),
  (322, 9),
  (41, 9),
  (13, 9),
  (500, 9),
  (6, 0),
  (51, 3),
  (109, 0),
  (1, 0),
  (202, 8)],
 [(201, 0), (56, 3), (9, 0), (5, 0), (1, 0), (1823, 1), (549, 1)],
 [(3, 0),
  (1, 0),
  (262, 6),
  (1714, 6),
  (2040, 6),
  (1196, 6),
  (18, 0),
  (483, 9),
  (23, 9),
  (665, 9),
  (13, 9),
  (242, 9)],
 [(10, 0),
  (12, 0),
  (4, 0),
  (168, 2),
  (637, 0),
  (1, 0),
  (2028, 1),
  (13, 0),
  (83, 4),
  (457, 4

In [26]:
training_pairs = [data.transpose_training_pair(tp) for tp in training_pairs]

In [27]:
import multiplai.evals.nlu.model as model


In [28]:
n_words = len(embedding.token_to_idx.keys())
n_labels = len(all_entities)

In [48]:
#ctx = mx.gpu(0)
ctx = mx.cpu()

# encoder = EncoderRNN(embedding, hidden_size=32)
# decoder = Decoder(n_labels, context_size=32)

classifier = model.ClassifierRNN(embedding, hidden_size=32, max_labels=n_labels)


model.train_iters(training_pairs, classifier, ctx)

/home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/ve/lib/python3.6/site-packages/mxnet/gluon/parameter.py:862: UserWarning: Parameter 'classifierrnn6_embedding0_weight' is already initialized, ignoring. Set force_reinit=True to re-initialize.
  v.initialize(None, ctx, init, force_reinit=force_reinit)


epoch 0 iteration 100  avg loss:  0.9996870777411121
epoch 0 iteration 200  avg loss:  0.5259192316755265
epoch 0 iteration 300  avg loss:  0.3837368260057313
epoch 0 iteration 400  avg loss:  0.3907888170621458
epoch 0 iteration 500  avg loss:  0.37742485268089676
epoch 0 iteration 600  avg loss:  0.32256183769476754
epoch 0 iteration 700  avg loss:  0.2922892674821868
epoch 0 iteration 800  avg loss:  0.2496342801503358
epoch 0 iteration 900  avg loss:  0.27890839917617805
epoch 0 iteration 1000  avg loss:  0.23203426845546107
epoch 0 iteration 1100  avg loss:  0.24586212219594536
epoch 0 iteration 1200  avg loss:  0.2869627609301784
epoch 0 iteration 1300  avg loss:  0.23423330208770718
epoch 0 iteration 1400  avg loss:  0.28758547871948253
epoch 0 iteration 1500  avg loss:  0.26269000699363404
epoch 0 iteration 1600  avg loss:  0.24087781661764532
epoch 0 iteration 1700  avg loss:  0.21488571407079488
epoch 0 iteration 1800  avg loss:  0.23888857753905057
epoch 0 iteration 1900  av

epoch 7 iteration 1900  avg loss:  0.015134021644173023
epoch 8 iteration 100  avg loss:  0.0911168598809164
epoch 8 iteration 200  avg loss:  0.026282603786599027
epoch 8 iteration 300  avg loss:  0.032596010673764206
epoch 8 iteration 400  avg loss:  0.021457817890343497
epoch 8 iteration 500  avg loss:  0.02859933948995352
epoch 8 iteration 600  avg loss:  0.022443550614120625
epoch 8 iteration 700  avg loss:  0.023536609295769
epoch 8 iteration 800  avg loss:  0.016642505443077125
epoch 8 iteration 900  avg loss:  0.031213739922480076
epoch 8 iteration 1000  avg loss:  0.03539303594231327
epoch 8 iteration 1100  avg loss:  0.014436263468919242


KeyboardInterrupt: 

In [47]:
%debug

> /home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/multiplai/evals/nlu/model.py(110)train()
    108             loss = F.add(loss,
    109                          criterion(pred=classifier_outputs[di],
--> 110                                    labels=target_variable[di]))
    111             # print(criterion(decoder_outputs[di], target_variable[di]))
    112 

ipdb> criterion
SoftmaxCrossEntropyLoss(batch_axis=0, w=None)
ipdb> q


In [60]:
model.eval(training_pairs[0:], classifier, ctx, debug=False)

{'total_examples': 1999, 'total_example_errors': 1086, 'example_errors': {
  [[118 134 215   1  41  85   1 345]
   [  0   2   0   9   9   9   0   8]]
  <NDArray 2x8 @cpu(0)>, 
  [[  10   12    2  185    4    1   41  117   14 1885   81   34   30]
   [   0    0    0    2    0    9    9    9    0    6    6    6    6]]
  <NDArray 2x13 @cpu(0)>, 
  [[  10   12    2    3    7    4  622    2 1510   34 1936  816    1  206
    1160   33   30    8]
   [   0    0    0    0    0    0    0    0    9    9    9    9    0    6
       6    6    6    0]]
  <NDArray 2x18 @cpu(0)>, 
  [[  61   80    2    3    6  124   36  177   36  393    1 1380  190]
   [   0    0    0    0    0    9    9    9    9    9    0    1    1]]
  <NDArray 2x13 @cpu(0)>, 
  [[ 678  317  113  889 1450   26   12    5    4   45    8]
   [   0    9    0    0    0    5    0    0    0    3    0]]
  <NDArray 2x11 @cpu(0)>, 
  [[ 11  25   4  28 135  26  18 320 226]
   [  0   0   0   0   2   5   0   9   9]]
  <NDArray 2x9 @cpu(0)>, 
  [[ 

In [39]:
%debug

> /home/daniel/Projects/meta-lifelong-learning/deep-neuroevolution/ve/lib/python3.6/site-packages/mxnet/base.py(253)check_call()
    251     """
    252     if ret != 0:
--> 253         raise MXNetError(py_str(_LIB.MXGetLastError()))
    254 
    255 

ipdb> q


In [45]:
data.get_entity_to_idx(all_entities)

{'<none>': 0,
 'city': 1,
 'condition_description': 2,
 'condition_temperature': 3,
 'country': 4,
 'current_location': 5,
 'geographic_poi': 6,
 'spatial_relation': 7,
 'state': 8,
 'timeRange': 9}

In [ ]:
# NEXT STEPS:
# !! test on actual test data, not just training data

# lower case everything...most of teh crap in wordvec in zero anyway! 
# maybe load glove?
# maybe give up on existing embeddings and train a separate (char) RNN
#   - could train a next-char predictor to get unsupervised feature extraction from large background corpus
#   - this might be a great level-2 proof of concept once the meta learning thing works at all

# overall: 
# - simple predictor does work and gets trained on this data set
# - some cues are confusing given lack of distinct embeddings for times and places
#
# - question: how good do i actually need to make the simple model here?
# - train it on multiple intents?
# -
